name: Deploy Branch to Cloudflare Pages

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  deploy-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Deploy to Cloudflare Pages
        id: cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=ruaphone --branch=${{ github.ref_name }}
      
      - name: Add deployment URL to PR
        if: github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const deploymentUrl = `https://${branch}.ruaphone.pages.dev`;
            
            // Find PRs for this branch
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${branch}`,
              state: 'open'
            });
            
            if (prs.length > 0) {
              const pr = prs[0];
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `🚀 Branch deployed to Cloudflare Pages!\n\nPreview URL: ${deploymentUrl}\n\n_This preview will be updated automatically with new commits._`
              });
            }
            
            // Output the URL for workflow logs
            console.log(`Deployment URL: ${deploymentUrl}`);